<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Головна
            <small>статистика та повідомлення</small>
        </h1>        
    </div>
</div>
<div class="row">
	<div class="col-md-2">
	    <div class="panel panel-primary">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-comments fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$unreadMessages?></div>
	                    <div>Листів</div>
	                </div>
	            </div>
	        </div>
	        <a href="#messages">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
	<div class="col-md-2">
	    <div class="panel panel-green">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-picture-o fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$photos?></div>
	                    <div>Фото</div>
	                </div>
	            </div>
	        </div>
	        <a href="/admin/photo">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
	<div class="col-md-2">
	    <div class="panel panel-yellow">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-newspaper-o fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$news?></div>
	                    <div>Новин</div>
	                </div>
	            </div>
	        </div>
	        <a href="/admin/news">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
	<div class="col-md-2">
	    <div class="panel panel-success">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-music fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$music?></div>
	                    <div>Пісень</div>
	                </div>
	            </div>
	        </div>
	        <a href="/admin/music">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
	<div class="col-md-2">
	    <div class="panel panel-info">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-users fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$people?></div>
	                    <div>Учасників</div>
	                </div>
	            </div>
	        </div>
	        <a href="/admin/about">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
	<div class="col-md-2">
	    <div class="panel panel-red">
	        <div class="panel-heading">
	            <div class="row">
	                <div class="col-xs-3">
	                    <i class="fa fa-camera fa-3x"></i>
	                </div>
	                <div class="col-xs-9 text-right">
	                    <div class="huge"><?=$video?></div>
	                    <div>Відеокліпів</div>
	                </div>
	            </div>
	        </div>
	        <a href="/admin/video">
	            <div class="panel-footer">
	                <span class="pull-left">Детальніше</span>
	                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                <div class="clearfix"></div>
	            </div>
	        </a>
	    </div>
	</div>
</div>
<?=(!empty($feedback)) ? $feedback : ''?>
<div class="table-container">
	<table class="table table-hover" id="messages">
		<thead>
			<tr>
				<th>Ім'я</th>
				<th>Email</th>
				<th>Телефон</th>
				<th>Текст</th>
				<th class="text-center">Дії</th>
			</tr>
		</thead>
		<tbody>
		<?php if (count($messages) > 0) :?>
			<?php foreach($messages as $message) :?>
			<tr data-id="<?=$message->id ?>" >
				<td class="cell-middle">
					<?php if ($message->unread) :?>
					<span class="label label-danger"><i class="fa fa-envelope"></i></span>
					<?php else :?>
					<span class="label label-info"><i class="fa fa-envelope-open-o"></i></span>
					<?php endif;?>
					
					<?=$message->name?>										
				</td>
				<td class="cell-middle">
					<?=$message->email ?>
				</td>
				<td class="cell-middle">
					<?=$message->phone?>					
				</td>
				<td class="cell-middle">
					<?=$message->content?>					
				</td>
				<td class="text-center">
					<div class="btn-group">
					<?php if ($message->unread) :?>
						<a data-read-link="/admin/read/<?=$message->id ?>" title="Прочитати" class="btn btn-primary read">
							<i class="fa fa-eye"></i>
						</a>
					<?php endif;?> 
						<a href="#modal" data-toggle='modal' title="Видалити" data-link="/admin/delete/<?=$message->id ?>" class="btn btn-danger delete">
							<i class="fa fa-times"></i>
						</a> 
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		<?php else :?>
			<td colspan="6" class="cell-middle">
				<div class="note note-info text-center">
				    <h4>
				        Немає повідомлень, поки що...
				    </h4>			    
				</div>
			</td>
		<?php endif;?>
		</tbody>		
	</table>
 </div>
 <div class="results"></div>
<div style="display: none;" class="modal fade" id="modal" role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header borderless">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
				<h4 class="modal-title">Видалити повідомлення?</h4>
			</div>
			<div class="modal-body">
				<form method="post" class = "delete_form">
					<input type="hidden" name="id" class="id-modal" />
					<button type="submit" name ="submit" class="btn btn-danger">
						Так
					</button>
					<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">
						Ні 
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('.delete').on("click", function () {
	var link = $(this).closest("a.delete");
	var	url = link.data("link");
	var tr = $(this).closest("tr");
	var	id = tr.data("id");
	$('.delete_form').attr("action", url);
	$('.id-modal').attr("value", id);
});
$('.read').on("click", function () {
	var link = $(this).closest("a.read");
	var	url = link.data("read-link");
	var tr = $(this).closest("tr");
	var	id = tr.data("id");	
	
	$.ajax({
	  type: 'POST',
	  url: url,
	  
	  success: function(data) {
	  	changeRow(data);
		//$('.results').html(data);
		console.log(data);
	  },
	  error:  function(xhr, str){
		console.log('Помилка: ' + xhr.responseCode);
	  }
	});
	var changeRow = function(data)
	{
		tr.find('span').removeClass('label-danger');
		tr.find('span').addClass('label-info');
		tr.find('span').html(data);
		tr.find('.read').hide();
	}
});
</script>