<div class="container">
  <form class="form-signin" method = "post">
	<h2 class="form-signin-heading text-center">Вхід у систему</h2>
	<label for="inputLogin" class="sr-only">Логін</label>
	<input id="inputLogin" class="form-control" type="text" name = "login" placeholder = "Логін" required autofocus>
	<label for="inputPassword" class="sr-only">Пароль</label>
	<input id="inputPassword" class="form-control" type="password" name = "password" placeholder = "Пароль" required>
	<button class="btn btn-lg btn-primary btn-block" name="submit" type="submit">Увійти</button>
  </form>
</div>
