<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <title>Єєєєйй!! Ти добралась</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/assets/greet/css/base.css">
    <link rel="stylesheet" href="/assets/greet/css/vendor.css">
    <link rel="stylesheet" href="/assets/greet/css/main.css">
    <script src="/assets/greet/js/modernizr.js"></script>
    <script src="/assets/greet/js/pace.min.js"></script>
    <link rel="shortcut icon" href="/assets/greet/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/assets/greet/favicon.ico" type="image/x-icon">
</head>
<body id="top">
<header class="s-header">
    <div class="header-logo">
        <a class="site-logo" href="index.html">
            <img src="/assets/greet/images/phr/logo.png" alt="Homepage">
        </a>
    </div>
    <nav class="header-nav">
        <a href="#0" class="header-nav__close" title="close"><span>Закрий</span></a>

        <div class="header-nav__content">
            <h3>Вуси Опакуй</h3>

            <ul class="header-nav__list">
                <li class="current"><a class="smoothscroll"  href="#home" title="home">Home</a></li>
                <li><a class="smoothscroll"  href="#about" title="about">About</a></li>
                <li><a class="smoothscroll"  href="#services" title="services">Services</a></li>
                <li><a class="smoothscroll"  href="#works" title="works">Works</a></li>
                <li><a class="smoothscroll"  href="#contact" title="contact">Contact</a></li>
            </ul>
        </div>
    </nav>
    <a class="header-menu-toggle" href="#0">
        <span class="header-menu-icon"></span>
    </a>
</header>

<section id="home" class="s-home target-section" data-parallax="scroll" data-image-src="/assets/greet/images/phr/pth-main.jpg" data-natural-width=3000 data-natural-height=2000 data-position-y=top>

    <div class="shadow-overlay"></div>

    <div class="home-content">

        <div class="row home-content__main">
            <h1>
                Урра! Вітаю з днем народження.
            </h1>

            <p>
                Нехай цей день принесе тобі стільки приємностей, позитиву, фану угару і сюрпризів скільки ти шерсті на шкурі твого кота!!!
            </p>
        </div>

    </div>

    <ul class="home-sidelinks">
        <li><a class="smoothscroll" href="#about">About<span>who we are</span></a></li>
        <li><a class="smoothscroll" href="#services">Services<span>what we do</span></a></li>
        <li><a  class="smoothscroll" href="#contact">Contact<span>get in touch</span></a></li>
    </ul>
    <a href="#about" class="home-scroll smoothscroll">
        <span class="home-scroll__text">Крути вниз</span>
        <span class="home-scroll__icon"></span>
    </a>

</section>

<!--<section id='about' class="s-about">

    <div class="row section-header" data-aos="fade-up">
        <div class="col-full">
            <h1 class="display-1">We are a group of design driven individuals passionate about creating beautiful UI designs.</h1>
        </div>
    </div>

    <div class="row" data-aos="fade-up">
        <div class="col-full">
            <p class="lead">
                Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.
            </p>
        </div>
    </div>

    <div class="row">

        <div class="about-process process block-1-2 block-tab-full">

            <div class="process__vline-left"></div>
            <div class="process__vline-right"></div>

            <div class="col-block process__col" data-item="1" data-aos="fade-up">
                <div class="process__text">
                    <h4>Define</h4>

                    <p>
                        Quos dolores saepe mollitia deserunt accusamus autem reprehenderit. Voluptas facere animi explicabo non quis magni recusandae.
                        Numquam debitis pariatur omnis facere unde. Laboriosam minus amet nesciunt est. Et saepe eos maxime tempore quasi deserunt ab.
                    </p>
                </div>
            </div>
            <div class="col-block process__col" data-item="2" data-aos="fade-up">
                <div class="process__text">
                    <h4>Design</h4>

                    <p>
                        Quos dolores saepe mollitia deserunt accusamus autem reprehenderit. Voluptas facere animi explicabo non quis magni recusandae.
                        Numquam debitis pariatur omnis facere unde. Laboriosam minus amet nesciunt est. Et saepe eos maxime tempore quasi deserunt ab.
                    </p>
                </div>
            </div>
            <div class="col-block process__col" data-item="3" data-aos="fade-up">
                <div class="process__text">
                    <h4>Build</h4>

                    <p>
                        Quos dolores saepe mollitia deserunt accusamus autem reprehenderit. Voluptas facere animi explicabo non quis magni recusandae.
                        Numquam debitis pariatur omnis facere unde. Laboriosam minus amet nesciunt est. Et saepe eos maxime tempore quasi deserunt ab.
                    </p>
                </div>
            </div>
            <div class="col-block process__col" data-item="4" data-aos="fade-up">
                <div class="process__text">
                    <h4>Launch</h4>

                    <p>
                        Quos dolores saepe mollitia deserunt accusamus autem reprehenderit. Voluptas facere animi explicabo non quis magni recusandae.
                        Numquam debitis pariatur omnis facere unde. Laboriosam minus amet nesciunt est. Et saepe eos maxime tempore quasi deserunt ab.
                    </p>
                </div>
            </div>

        </div>

    </div>

</section>-->


<!-- services
================================================== -->
<section id='services' class="s-services light-gray">

    <div class="row section-header" data-aos="fade-up">
        <div class="col-full">
            <h3 class="subhead">начньомс</h3>
            <h1 class="display-1">Спочатку треба щось дженерал таке, щоб розігртися</h1>
        </div>
    </div>

    <div class="row" data-aos="fade-up">
        <div class="col-full">
            <p class="lead">
                Як ти бачиш, я настільки лінива тварюка став, що навіть впадло щось верстати було, тому скомуніздив з тирнетів харявний лендінг шаблон, додав котів і вуаля. Ну, добре, хоч, побажання сам писав, не суди строго. Вибач канєшн, що не позвонив, але я думаю, що для нас обох так простіше. Ну да ладно, чот я розпиздівся, друга сторінка, а побажань все німа. Тому в цей день особливо, але хай нижческазане арбайтен кожен день, бажаю:
            </p>
        </div>
    </div>

    <div class="row services-list block-1-3 block-m-1-2 block-tab-full">

        <div class="col-block service-item " data-aos="fade-up">
            <div class="service-icon service-icon--brand-identity">
                <i class="fa fa-heartbeat"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Міцного здров'я</h3>
                <p>Будь здоровою і сильною, як фізично, так і душевно. Це не значить твою абілку підняти 100кг вантажу і викинути його через вікно. То значить мати
                  силу вставати кожен день і робити щось хороше як для себе, так і для близьких, або щось погане для недругів, мухахахаха.
                  Щоб всякі волохаті і гнусні бактерії і віруси уйобали від тебе в невідомому напрямку і в дикому ужасі, вчені занесли їх в червону книгу,
                  а аптеки розорились к хуям і продавали тільки вітьків. Щоб в тебе було стільки енергії, що аж всі лампочки починали горіти від тебе в радіусі 20м.
                </p>
            </div>
        </div>

        <div class="col-block service-item" data-aos="fade-up">
            <div class="service-icon  service-icon--illustration">
                <i class="fa fa-brain"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Миру і спокою в голові</h3>
                <p>Дай пизди і покажи хто в зданії батя всім своїм демонам в голові. Я сірожно, ці тварі взагалі знахабніли
                  і розпоясалися. Ти вже вийшла на стежку війни з ними, тому пам'ятай, томагавк чоп із йо дес блоу! Побори всіх демонів,
                  які тобі нічого не дають, а лише забирають. То такі ублюдки як Страх, Біль, Униніє, Сум, Тривога. Зітри їх в порошок,
                  а порошок змішай з гівном і викинь. З іншими тварями, такими як Злість і Гнів, Гординя договорись, але сильно контролю їм
                  не давай, став свої умови, щоб вони давали свій ефект тоді, коли вигідно тобі. І слова "Іди ти нахуй" постав собі у бистро вживані.
                  <em>можна просто "ні"</em>
                </p>
            </div>
        </div>

        <div class="col-block service-item" data-aos="fade-up">
            <div class="service-icon  service-icon--web-design">
                <i class="fa fa-clock"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Мати контроль над часом</h3>
                <p>Щоб ти встигала зробити все, що ти задумала на день, сидиш така, і думаєш, єбаать, явже все зробила, а тут
                  щойно тільки 11 годин. Гм, треба кароч саморозвиватися, хулє. Щоб ти прокидалася вранці як люди в йобаних
                  рекламах нескафе, і кожен ранок був для тебе і справді добрим. Щоб вистачало часу на кота, родичів, всіх друзів
                  і близьких. (помітила приорітет, лол?). Щоб ти мала час на книжки, фільми, прогулянки та ігри (необовязково
                  комп'ютерні, хоча спробувати треба, едік не в щот) і просто витягнутися і подумати "як же круто тут і зараз, курва".
                </p>
            </div>
        </div>

        <div class="col-block service-item" data-aos="fade-up">
            <div class="service-icon service-icon--product-strategy">
                <i class="fa fa-battery-full"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Енергії та мотивації</h3>
                <p>Хотіти щось робити - ахуєнно. Бажаю тобі щоб ти загорілась (ну не буквально, йопт) чимось. Чи то сколотити
                  якусь банду з гітарами, скрипками і бубном, чи то відкрити якусь свою справу і єбошити, чи просто зібрати бебехи,
                  дати кота мені на зберігання і свалити куди подалі помандрувати, чи просто зробити жрат і прибрати барліг.
                  Просто відчуй себе як в 16 - коли тобі похуй на все, ти знаєш, що всі дороги відкриті і перепон для тебе просто
                  не існує. Щоб кожен день тобі приносив нові емоції та враження, все те, що робить нас живими.
                </p>
            </div>
        </div>

        <div class="col-block service-item" data-aos="fade-up">
            <div class="service-icon  service-icon--ui-design">
                <i class="fa fa-heart"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Кохання та пристрасті</h3>
                <p>Бажаю знов тобі відчути себе закоханою, ту ейфорію, піднесення і настрій. Вчені кажуть, що то просто хімія, але я
                  не вірю, інакше досі були б охуєнні наркотики з таким же ефектом. Бабочок і животі тобі і всього такого (ніколи не
                  відчував бабочок, хіба що макарони, але то може тікі у дівчат). Щоб тобі завжди хотілося бути з коханою людиною,
                  відчувати її думки і бажання, і стати для неї дійно рідною. Щоб не потрібно було "строїти отношенія", щоб вони
                  будувались самі на довірі, ласці, любові та злагоді. Щоб всі суперечки та сварки закінчували прям на місці жосским
                  трахом, і все приходило в норму. Щоб твій партнер надихав на якісь справи чи слова, і так само, надихай його.
                </p>
            </div>
        </div>

        <div class="col-block service-item" data-aos="fade-up">
            <div class="service-icon service-icon--mobile-dev">
                <i class="fa fa-briefcase"></i>
            </div>
            <div class="service-text">
                <h3 class="h4">Успіху та прогресу в роботі</h3>
                <p>Бажаю тобі успіху, кар'єрного (не від слова "кар'єр") росту. Щоб не приходилось продирати баньки і піздувати на
                  "всратую галєру", а норм вставати і іти на роботу яка приносить не лише бапки, а й ніхуйовеньке таке задоволення
                  і радість від процесу її виконання. Легких і незайобистих тобі тікетів, розумніших за макаку клієнтів, розуміючих
                  і підтримуючих колєг (задохуя дієприслівників, але я єбу як його прально сказати), щоб заржавіла корпоративна машина
                  получила ведешки в свої єбучі шестерні крутилася швидко в ту строну і в той час, коли ти цього потребуєш. І, звичайно,
                  щоб за свою працю ти отримувала достойну єбіческих розмірів купу бабла в біткоєнах.
                </p>
            </div>
        </div>

      <div class="col-block service-item" data-aos="fade-up">
        <div class="service-icon service-icon--product-strategy">
          <i class="fa fa-chart-line"></i>
        </div>
        <div class="service-text">
          <h3 class="h4">Знань та вміння їх застосовувати</h3>
          <p>Бажаю кожен день дізнаватися щось нове. Пох, що це, закон Ома для паралельних з'єднань, типи наднових зірок  чи 25
            способів укласти макіяж не як в шлюхи. Кожен день поглиблювати і налаштовувати зв'язки між нейронами ахуєнно, це надає
            кльове відчуття (it was this moment that he knew: HE`S A FUACKING GOD) і запобігає унінію та прокрастинації. Забудь слова
            "та нахуй воно мені нада, я його ніколи не використаю", вибирай знання по тому, цікаво то тобі чи ні, і все получиться.
          </p>
        </div>
      </div>

      <div class="col-block service-item" data-aos="fade-up">
        <div class="service-icon  service-icon--ui-design">
          <i class="fa fa-smile-wink"></i>
        </div>
        <div class="service-text">
          <h3 class="h4">Гарно виглядай</h3>
          <p>Нікому не секрет, що ти афігеть яка ахуєнно, ні, навіть не так, АХУЄННО, отак, гарна. Бажаю тобі і надалі залишатися
            такою, за винятком того, щоб тікі мішки позлазили з очей, набились грішми, або хоча б туфлями які не жмуть і не натирають
            чи сорочками приталеними і по розміру, і полізли в шкаф, або де їм там місце. Щоб невбаганний ітератор часу прибавляв тобі
            вік лише в паспорт, і щоб цей документ був бажаним для продавців алкашки ще багато-багато років.
          </p>
        </div>
      </div>

      <div class="col-block service-item" data-aos="fade-up">
        <div class="service-icon service-icon--mobile-dev">
          <i class="fa fa-dollar-sign"></i>
        </div>
        <div class="service-text">
          <h3 class="h4">Єбічеських розмірів купу бабла</h3>
          <p>Бапки не головне, але вони, сука, рішають ахуєть як багато чого, тому бажаю, щоб в тебе їх було дохуя. А якщо серйозно,
            то хай до тебе прийде білл гейст, і скаже, бля, чот я хочу новий віндовс, випустити, а бабок німа, бо ті срані деви на
            до дієзі взагалі зажрались, жиди йобані, короч, позич пару лярдів, ну хулі тобі стоїть. А ти така, допиваючи молочко, витираєш
            з остатки вюсів соткою, кажеш, ну ладно, так і бить, позичу, але з тебе ліцензійний кряк для мене і льошки пожизнєнно, плюс
            в синьому екрані смайлик буде :) замість :(
          </p>
        </div>
      </div>
    </div>
</section>


<!-- works
================================================== -->
<section id='works' class="s-works">

    <div class="row section-header" data-aos="fade-up">
        <div class="col-full">
            <h3 class="subhead">Featured Works</h3>
            <h1 class="display-1">These are some of our recent design projects and we are so excited to show them to you.</h1>
        </div>
    </div> <!-- end section-header -->

    <div class="row masonry-wrap">
        <div class="masonry">

            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-lamp.jpg" class="thumb-link" title="Lamp" data-size="1050x700">
                            <img src="/assets/greet/images/phr/kakit.jpg" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Lamp
                        </h3>
                        <p class="item-folio__cat">
                            Web Design
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <div class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </div>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-salad.jpg" class="thumb-link" title="Salad" data-size="1050x700">
                            <img src="/assets/greet/images/phr/ptx+friends.jpg" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Salad
                        </h3>
                        <p class="item-folio__cat">
                            Branding
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <span class="item-folio__caption">
                            <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                        </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-woodcraft.jpg" class="thumb-link" title="Woodcraft" data-size="1050x700">
                            <img src="/assets/greet/images/portfolio/woodcraft.jpg"
                                 srcset="/assets/greet/images/portfolio/woodcraft.jpg 1x, /assets/greet/images/portfolio/woodcraft@2x.jpg 2x" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Woodcraft
                        </h3>
                        <p class="item-folio__cat">
                            Branding
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <span class="item-folio__caption">
                            <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                        </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-liberty.jpg" class="thumb-link" title="Liberty" data-size="1050x700">
                            <img src="/assets/greet/images/portfolio/liberty.jpg"
                                 srcset="/assets/greet/images/portfolio/liberty.jpg 1x, /assets/greet/images/portfolio/liberty@2x.jpg 2x" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Liberty
                        </h3>
                        <p class="item-folio__cat">
                            Web Development
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <span class="item-folio__caption">
                            <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                        </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->


            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-fuji.jpg" class="thumb-link" title="Fuji" data-size="1050x700">
                            <img src="/assets/greet/images/portfolio/fuji.jpg"
                                 srcset="/assets/greet/images/portfolio/fuji.jpg 1x, /assets/greet/images/portfolio/fuji@2x.jpg 2x" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Fuji
                        </h3>
                        <p class="item-folio__cat">
                            Web Design
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <span class="item-folio__caption">
                            <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                        </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick" data-aos="fade-up">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/assets/greet/images/portfolio/gallery/g-shutterbug.jpg" class="thumb-link" title="Shutterbug" data-size="1050x700">
                            <img src="/assets/greet/images/portfolio/shutterbug.jpg"
                                 srcset="/assets/greet/images/portfolio/shutterbug.jpg 1x, /assets/greet/images/portfolio/shutterbug@2x.jpg 2x" alt="">
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Lady Shutterbug
                        </h3>
                        <p class="item-folio__cat">
                            Branding
                        </p>
                    </div>

                    <a href="https://www.behance.net/" class="item-folio__project-link" title="Project link">
                        Project Link
                    </a>

                    <span class="item-folio__caption">
                            <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                        </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

        </div> <!-- end masonry -->
    </div> <!-- end masonry-wrap -->

    <div class="testimonials-wrap" data-aos="fade-up">

        <div class="row">
            <div class="col-full testimonials-header">
                <h2 class="h1">What Clients Are Saying.</h2>
            </div>
        </div>

        <div class="row testimonials">

            <div class="col-full testimonials__slider">

                <div class="testimonials__slide">
                    <img src="/assets/greet/images/avatars/user-01.jpg" alt="Author image" class="testimonials__avatar">
                    <p>Qui ipsam temporibus quisquam velMaiores eos cumque distinctio nam accusantium ipsum.
                        Laudantium quia consequatur molestias delectus culpa facere hic dolores aperiam. Accusantium quos qui praesentium corpori.</p>
                    <div class="testimonials__author">
                        Tim Cook
                        <span>CEO, Apple</span>
                    </div>
                </div> <!-- end testimonials__slide -->

                <div class="testimonials__slide">
                    <img src="/assets/greet/images/avatars/user-05.jpg" alt="Author image" class="testimonials__avatar">
                    <p>Excepturi nam cupiditate culpa doloremque deleniti repellat. Veniam quos repellat voluptas animi adipisci.
                        Nisi eaque consequatur. Quasi voluptas eius distinctio. Atque eos maxime. Qui ipsam temporibus quisquam vel.</p>
                    <div class="testimonials__author">
                        Sundar Pichai
                        <span>CEO, Google</span>
                    </div>
                </div> <!-- end testimonials__slide -->

                <div class="testimonials__slide">
                    <img src="/assets/greet/images/avatars/user-02.jpg" alt="Author image" class="testimonials__avatar">
                    <p>Repellat dignissimos libero. Qui sed at corrupti expedita voluptas odit. Nihil ea quia nesciunt. Ducimus aut sed ipsam.
                        Autem eaque officia cum exercitationem sunt voluptatum accusamus. Quasi voluptas eius distinctio.</p>
                    <div class="testimonials__author">
                        Satya Nadella
                        <span>CEO, Microsoft</span>
                    </div>
                </div> <!-- end testimonials__slide -->

            </div> <!-- end testimonials__slider -->

        </div> <!-- end testimonials -->

    </div> <!-- end testimonials-wrap -->

</section> <!-- end s-works -->


<!-- stats
================================================== -->
<section id="stats" class="s-stats">

    <div class="row stats block-1-4 block-m-1-2 block-mob-full" data-aos="fade-up">

        <div class="col-block stats__col ">
            <div class="stats__count">129</div>
            <h5>Awards Received</h5>
        </div>
        <div class="col-block stats__col">
            <div class="stats__count">1507</div>
            <h5>Cups of Coffee</h5>
        </div>
        <div class="col-block stats__col">
            <div class="stats__count">108</div>
            <h5>Projects Completed</h5>
        </div>
        <div class="col-block stats__col">
            <div class="stats__count">103</div>
            <h5>Happy Clients</h5>
        </div>

    </div> <!-- end stats -->

</section> <!-- end s-stats -->


<!-- contact
================================================== -->
<section id="contact" class="s-contact">

    <div class="row section-header" data-aos="fade-up">
        <div class="col-full">
            <h3 class="subhead subhead--light">Contact Us</h3>
            <h1 class="display-1 display-1--light">Get in touch and let's make something great together. Let's turn your idea on an even greater product.</h1>
        </div>
    </div> <!-- end section-header -->

    <div class="row">

        <div class="col-full contact-main" data-aos="fade-up">
            <p>
                <a href="mailto:#0" class="contact-email">hello@transcend-studio.com</a>
                <span class="contact-number">+1 (917) 123 456  /  +1 (917) 333 987</span>
            </p>
        </div> <!-- end contact-main -->

    </div> <!-- end row -->

    <div class="row">

        <div class="col-five tab-full contact-secondary" data-aos="fade-up">
            <h3 class="subhead subhead--light">Where To Find Us</h3>

            <p class="contact-address">
                1600 Amphitheatre Parkway<br>
                Mountain View, CA<br>
                94043 US
            </p>
        </div> <!-- end contact-secondary -->

        <div class="col-five tab-full contact-secondary" data-aos="fade-up">
            <h3 class="subhead subhead--light">Follow Us</h3>

            <ul class="contact-social">
                <li>
                    <a href="#0"><i class="fab fa-facebook"></i></a>
                </li>
                <li>
                    <a href="#0"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                    <a href="#0"><i class="fab fa-instagram"></i></a>
                </li>
                <li>
                    <a href="#0"><i class="fab fa-behance"></i></a>
                </li>
                <li>
                    <a href="#0"><i class="fab fa-dribbble"></i></a>
                </li>
            </ul> <!-- end contact-social -->

            <div class="contact-subscribe">
                <form id="mc-form" class="group mc-form" novalidate="true">
                    <input type="email" value="" name="EMAIL" class="email" id="mc-email" placeholder="Email Address" required="">
                    <input type="submit" name="subscribe" value="Subscribe">
                    <label for="mc-email" class="subscribe-message"></label>
                </form>
            </div> <!-- end contact-subscribe -->
        </div> <!-- end contact-secondary -->

    </div> <!-- end row -->

    <div class="row">
        <div class="col-full cl-copyright">
                <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
        </div>
    </div>

    <div class="cl-go-top">
        <a class="smoothscroll" title="Back to Top" href="#top"><i class="icon-arrow-up" aria-hidden="true"></i></a>
    </div>

</section> <!-- end s-contact -->


<!-- photoswipe background
================================================== -->
<div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">

    <div class="pswp__bg"></div>
    <div class="pswp__scroll-wrap">

        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <div class="pswp__counter"></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button> <button class="pswp__button pswp__button--share" title=
                "Share"></button> <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button> <button class="pswp__button pswp__button--zoom" title=
                "Zoom in/out"></button>
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
            </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button> <button class="pswp__button pswp__button--arrow--right" title=
            "Next (arrow right)"></button>
            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>

    </div>

</div> <!-- end photoSwipe background -->


<!-- preloader
================================================== -->
<div id="preloader">
    <div id="loader">
    </div>
</div>


<!-- Java Script
================================================== -->
<script src="/assets/greet/js/jquery-3.2.1.min.js"></script>
<script src="/assets/greet/js/plugins.js"></script>
<script src="/assets/greet/js/main.js"></script>

</body>

</html>