<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">
  <title>Єєєєйй!! Ти добралась</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/assets/greet/css/base.css">
  <link rel="stylesheet" href="/assets/greet/css/vendor.css">
  <link rel="stylesheet" href="/assets/greet/css/main.css">
  <script src="/assets/greet/js/modernizr.js"></script>
  <script src="/assets/greet/js/pace.min.js"></script>
  <link rel="shortcut icon" href="/assets/greet/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/assets/greet/favicon.ico" type="image/x-icon">
</head>
<body id="top">
<header class="s-header">
  <div class="header-logo">
    <a class="site-logo" href="index.html">
      <img src="/assets/greet/images/phr/logo.png" alt="Homepage">
    </a>
  </div>
  <nav class="header-nav">
    <a href="#0" class="header-nav__close" title="close"><span>Закрий</span></a>

    <div class="header-nav__content">
      <h3>Вуси Опакуй</h3>

      <ul class="header-nav__list">
        <li class="current"><a class="smoothscroll" href="#home" title="Верх">Верх</a></li>
        <li><a class="smoothscroll" href="#words" title="Слова">Слова</a></li>
        <li><a class="smoothscroll" href="#pics" title="Картинки">Картинки</a></li>
      </ul>
    </div>
  </nav>
  <a class="header-menu-toggle" href="#0">
    <span class="header-menu-icon"></span>
  </a>
</header>

<section id="home" class="s-home target-section" data-parallax="scroll" data-image-src="/assets/greet/images/phr/pth-main.jpg"
         data-natural-width=3000 data-natural-height=2000 data-position-y=top>

  <div class="shadow-overlay"></div>

  <div class="home-content">

    <div class="row home-content__main">
      <h1>
        Урра! Вітаю з днем народження.
      </h1>

      <p>
        Нехай цей день принесе тобі стільки приємностей, позитиву, фану угару і сюрпризів скільки ти шерсті на шкурі твого кота!!!
      </p>
    </div>

  </div>

  <ul class="home-sidelinks">
    <li><a class="smoothscroll" href="#words">Слова</a></li>
    <li><a class="smoothscroll" href="#pics">Картинки</a></li>
  </ul>
  <a href="#about" class="home-scroll smoothscroll">
    <span class="home-scroll__text">Крути вниз</span>
    <span class="home-scroll__icon"></span>
  </a>

</section>

<section id='words' class="s-services light-gray">

  <div class="row section-header" data-aos="fade-up">
    <div class="col-full">
      <h3 class="subhead">начньомс</h3>
      <h1 class="display-1">Вітаю!!!</h1>
    </div>
  </div>

  <div class="row" data-aos="fade-up">
    <div class="col-full">
      <p class="lead">
        Як ти бачиш, я настільки лінива тварюка став, що навіть впадло щось верстати було, тому скомуніздив з тирнетів харявний
        лендінг шаблон, додав котів і вуаля. Ну, добре, хоч, побажання сам писав, не суди строго. Вибач канєшн, що не позвонив,
        але я думаю, що для нас обох так простіше. Ну да ладно, чот я розпиздівся, друга сторінка, а побажань все німа. Тому в цей
        день особливо, але хай нижческазане арбайтен кожен день, бажаю:
      </p>
    </div>
  </div>

  <div class="row services-list block-1-3 block-m-1-2 block-tab-full">

    <div class="col-block service-item " data-aos="fade-up">
      <div class="service-icon service-icon--brand-identity">
        <i class="fa fa-heartbeat"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Міцного здров'я</h3>
        <p>Будь здоровою і сильною, як фізично, так і душевно. Це не значить твою абілку підняти 100кг вантажу і викинути його
          через вікно. То значить мати
          силу вставати кожен день і робити щось хороше як для себе, так і для близьких, або щось погане для недругів, мухахахаха.
          Щоб всякі волохаті і гнусні бактерії і віруси уйобали від тебе в невідомому напрямку і в дикому ужасі, вчені занесли їх
          в червону книгу,
          а аптеки розорились к хуям і продавали тільки вітьків. Щоб в тебе було стільки енергії, що аж всі лампочки починали
          горіти від тебе в радіусі 20м.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon  service-icon--illustration">
        <i class="fa fa-brain"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Миру і спокою в голові</h3>
        <p>Дай пизди і покажи хто в зданії батя всім своїм демонам в голові. Я сірожно, ці тварі взагалі знахабніли
          і розпоясалися. Ти вже вийшла на стежку війни з ними, тому пам'ятай, томагавк чоп із йо дес блоу! Побори всіх демонів,
          які тобі нічого не дають, а лише забирають. То такі ублюдки як Страх, Біль, Униніє, Сум, Тривога. Зітри їх в порошок,
          а порошок змішай з гівном і викинь. З іншими тварями, такими як Злість і Гнів, Гординя договорись, але сильно контролю
          їм
          не давай, став свої умови, щоб вони давали свій ефект тоді, коли вигідно тобі. І слова "Іди ти нахуй" постав собі у
          бистро вживані.
          <em>можна просто "ні"</em>
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon  service-icon--web-design">
        <i class="fa fa-clock"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Мати контроль над часом</h3>
        <p>Щоб ти встигала зробити все, що ти задумала на день, сидиш така, і думаєш, єбаать, явже все зробила, а тут
          щойно тільки 11 годин. Гм, треба кароч саморозвиватися, хулє. Щоб ти прокидалася вранці як люди в йобаних
          рекламах нескафе, і кожен ранок був для тебе і справді добрим. Щоб вистачало часу на кота, родичів, всіх друзів
          і близьких. (помітила приорітет, лол?). Щоб ти мала час на книжки, фільми, прогулянки та ігри (необовязково
          комп'ютерні, хоча спробувати треба, едік не в щот) і просто витягнутися і подумати "як же круто тут і зараз, курва".
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon service-icon--product-strategy">
        <i class="fa fa-battery-full"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Енергії та мотивації</h3>
        <p>Хотіти щось робити - ахуєнно. Бажаю тобі щоб ти загорілась (ну не буквально, йопт) чимось. Чи то сколотити
          якусь банду з гітарами, скрипками і бубном, чи то відкрити якусь свою справу і єбошити, чи просто зібрати бебехи,
          дати кота мені на зберігання і свалити куди подалі помандрувати, чи просто зробити жрат і прибрати барліг.
          Просто відчуй себе як в 16 - коли тобі похуй на все, ти знаєш, що всі дороги відкриті і перепон для тебе просто
          не існує. Щоб кожен день тобі приносив нові емоції та враження, все те, що робить нас живими.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon  service-icon--ui-design">
        <i class="fa fa-heart"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Кохання та пристрасті</h3>
        <p>Бажаю знов тобі відчути себе закоханою, ту ейфорію, піднесення і настрій. Вчені кажуть, що то просто хімія, але я
          не вірю, інакше досі були б охуєнні наркотики з таким же ефектом. Бабочок і животі тобі і всього такого (ніколи не
          відчував бабочок, хіба що макарони, але то може тікі у дівчат). Щоб тобі завжди хотілося бути з коханою людиною,
          відчувати її думки і бажання, і стати для неї дійно рідною. Щоб не потрібно було "строїти отношенія", щоб вони
          будувались самі на довірі, ласці, любові та злагоді. Щоб всі суперечки та сварки закінчували прям на місці жосским
          трахом, і все приходило в норму. Щоб твій партнер надихав на якісь справи чи слова, і так само, надихай його.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon service-icon--mobile-dev">
        <i class="fa fa-briefcase"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Успіху та прогресу в роботі</h3>
        <p>Бажаю тобі успіху, кар'єрного (не від слова "кар'єр") росту. Щоб не приходилось продирати баньки і піздувати на
          "всратую галєру", а норм вставати і іти на роботу яка приносить не лише бапки, а й ніхуйовеньке таке задоволення
          і радість від процесу її виконання. Легких і незайобистих тобі тікетів, розумніших за макаку клієнтів, розуміючих
          і підтримуючих колєг (задохуя дієприслівників, але я єбу як його прально сказати), щоб заржавіла корпоративна машина
          получила ведешки в свої єбучі шестерні крутилася швидко в ту строну і в той час, коли ти цього потребуєш. І, звичайно,
          щоб за свою працю ти отримувала достойну єбіческих розмірів купу бабла в біткоєнах.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon service-icon--product-strategy">
        <i class="fa fa-chart-line"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Знань та вміння їх застосовувати</h3>
        <p>Бажаю кожен день дізнаватися щось нове. Пох, що це, закон Ома для паралельних з'єднань, типи наднових зірок чи 25
          способів укласти макіяж не як в шлюхи. Кожен день поглиблювати і налаштовувати зв'язки між нейронами ахуєнно, це надає
          кльове відчуття (it was this moment that he knew: HE`S A FUACKING GOD) і запобігає унінію та прокрастинації. Забудь
          слова
          "та нахуй воно мені нада, я його ніколи не використаю", вибирай знання по тому, цікаво то тобі чи ні, і все получиться.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon  service-icon--ui-design">
        <i class="fa fa-smile-wink"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Гарно виглядай</h3>
        <p>Нікому не секрет, що ти афігеть яка ахуєнно, ні, навіть не так, АХУЄННО, отак, гарна. Бажаю тобі і надалі залишатися
          такою, за винятком того, щоб тікі мішки позлазили з очей, набились грішми, або хоча б туфлями які не жмуть і не
          натирають
          чи сорочками приталеними і по розміру, і полізли в шкаф, або де їм там місце. Щоб невбаганний ітератор часу прибавляв
          тобі
          вік лише в паспорт, і щоб цей документ був бажаним для продавців алкашки ще багато-багато років.
        </p>
      </div>
    </div>

    <div class="col-block service-item" data-aos="fade-up">
      <div class="service-icon service-icon--mobile-dev">
        <i class="fa fa-dollar-sign"></i>
      </div>
      <div class="service-text">
        <h3 class="h4">Єбічеських розмірів купу бабла</h3>
        <p>Бапки не головне, але вони, сука, рішають ахуєть як багато чого, тому бажаю, щоб в тебе їх було дохуя. А якщо серйозно,
          то хай до тебе прийде білл гейст, і скаже, бля, чот я хочу новий віндовс, випустити, а бабок німа, бо ті срані деви на
          до дієзі взагалі зажрались, жиди йобані, короч, позич пару лярдів, ну хулі тобі стоїть. А ти така, допиваючи молочко,
          витираєш
          з остатки вюсів соткою, кажеш, ну ладно, так і бить, позичу, але з тебе ліцензійний кряк для мене і льошки пожизнєнно,
          плюс
          в синьому екрані смайлик буде :) замість :(
        </p>
      </div>
    </div>
  </div>
</section>

<section id='pics' class="s-works">

  <div class="row section-header" data-aos="fade-up">
    <div class="col-full">
      <h3 class="subhead">Фотки</h3>
      <h1 class="display-1">Трохи нарив фоток в інетах, чисто для ілюстрацій.</h1>
    </div>
  </div>

  <div class="row masonry-wrap">
    <div class="masonry">
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/ptx+friends.jpg" class="thumb-link" title="Розчехри пурхи" data-size="1280x720">
              <img src="/assets/greet/images/phr/ptx+friends.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Гарних тобі друзів
            </h3>
            <p class="item-folio__cat">
              Unfuck society
            </p>
          </div>


          <span class="item-folio__caption">
              <p>Самому гарно і круто бути тільки герою якогось кінофільму. Більше тобі людей, яких ти можеш називати друзями.</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">
          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/kakit.jpg" class="thumb-link" title="Мррррр. ПшПш" data-size="360x479">
              <img src="/assets/greet/images/phr/kakit.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Кокхка
            </h3>
            <p class="item-folio__cat">
              Котото
            </p>
          </div>

          <div class="item-folio__caption">
            <p>Тут без коментарів. Хоча ні, вюсів не хватає</p>
          </div>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/photo%231125.jpg" class="thumb-link" title="Concentrate" data-size="1536x2048">
              <img src="/assets/greet/images/phr/photo%231125.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Міцних тобі сорочок і концентрації в робботі
            </h3>
            <p class="item-folio__cat">
              Концентрація
            </p>
          </div>

          <span class="item-folio__caption">
              <p>Не знаю, що  ти там робила, але тут ти така сконцентрована і занята, що аж страх. Думаю, кльова фотка вийшла</p>
          </span>

        </div> <!-- end item-folio -->
      </div>

      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/ws-opk.jpg" class="thumb-link"
               data-size="640x480">
              <img src="/assets/greet/images/phr/ws-opk.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Гарної музики і натхнення грати
            </h3>
          </div>

          <span class="item-folio__caption">
              <p>Гарної музики тобі, щоб вона допомагала тобі відчути себе сильною. Треба побільше фоток з такою зухвалою мордою)</p>
          </span>

        </div> <!-- end item-folio -->
      </div>


      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/z_f6ccd470.jpg" class="thumb-link" title="Бринь" data-size="1050x700">
              <img src="/assets/greet/images/phr/z_f6ccd470.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Ламповості тобі затишку
            </h3>
            <p class="item-folio__cat">
              ТЛЗ
            </p>
          </div>

          <span class="item-folio__caption">
              <p>В цій фотці кльово все, і навіть нейлонові струни її не спортять). Побільше тобі лампової атмосфери, людей які допоможуть її створити </p>
          </span>

        </div> <!-- end item-folio -->
      </div>

      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/natal-gitar.jpg" class="thumb-link" title="Get overdriven" data-size="662x1000">
              <img src="/assets/greet/images/phr/natal-gitar.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              І не забувай про медіатор судьби, єбош мітол
            </h3>
            <p class="item-folio__cat">
              Get overdriven
            </p>
          </div>

          <span class="item-folio__caption">
              <p>Включи проц нарули щось жосске, і запіли мітол, і пох, що не вмієш, ніхто тебе не зупинить).</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/rnpXUK6j_yk.jpg" class="thumb-link"  data-size="1056x1667">
              <img src="/assets/greet/images/phr/rnpXUK6j_yk.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Купи буси
            </h3>
            <p class="item-folio__cat">
              😍
            </p>
          </div>


        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/3jTcslVM-kE.jpg" class="thumb-link" title="Wuss" data-size="1050x700">
              <img src="/assets/greet/images/phr/3jTcslVM-kE.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Відкорми кота
            </h3>
            <p class="item-folio__cat">
              Шкуротаааааа            </p>
          </div>
          <span class="item-folio__caption">
              <p>Зроби зі свого кошеняти отаку когтисту машину для вбивства. Буде прикольно, я гарантірую ето)</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/qkJL3ohgWAQ.jpg" class="thumb-link" data-size="2560x1920">
              <img src="/assets/greet/images/phr/qkJL3ohgWAQ.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Поїдь кудись і привези звідти лише позитивні спогади
            </h3>
            <p class="item-folio__cat">
              Драйву і екстриму
            </p>
          </div>


          <span class="item-folio__caption">
              <p>Драйву та екстриму тобі! Cпробуй усе в цьому житті і ні про що не жалій.</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/shkurr.jpg" class="thumb-link" title="Schkurrrr" data-size="3120x4160">
              <img src="/assets/greet/images/phr/shkurr.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Вусатого сторожа
            </h3>
            <p class="item-folio__cat">
              Котота
            </p>
          </div>
          <span class="item-folio__caption">
              <p>Котів тобі) Хай вусаті завжди сторожать тві сон, лікують, що болить, гріють та просто гарно мурчать.</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/pth-main.jpg" class="thumb-link" data-size="698x465">
              <img src="/assets/greet/images/phr/pth-main.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Бути в гарному настрої і такою ж гарною
            </h3>
          </div>


          <span class="item-folio__caption">
              <p>Веселих тобі прогулянок, гарних та щирих емоцій.</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/dsc-5410.jpg" class="thumb-link" data-size="999x667">
              <img src="/assets/greet/images/phr/dsc-5410.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Кльових тобі концертів!
            </h3>
          </div>
          <span class="item-folio__caption">
              <p>Кльових тобі концертів, сил і витримки відриватися на них по повній. І да, хай твої улюблені групи приїжають частіше.
                Щоб навіть лисий хуй протверезів від вінішка і притащив сюди свою банду</p>
          </span>

        </div> <!-- end item-folio -->
      </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/IMG_20171030_120736.jpg" class="thumb-link" title="Кокхка" data-size="3120x4160">
              <img src="/assets/greet/images/phr/IMG_20171030_120736.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Неконфілктних котогостей
            </h3>
            <p class="item-folio__cat">
              Вусота
            </p>
          </div>
          <span class="item-folio__caption">
              <p>Хай до тебе частіше приходять котогості, але щоб в них не було конфліктів з резидентними вусанами).</p>
          </span>
          </div>

        </div>
      <div class="masonry__brick" data-aos="fade-up">
        <div class="item-folio">

          <div class="item-folio__thumb">
            <a href="/assets/greet/images/phr/21587329_891989314283283_4888037390214767349_o.jpg" class="thumb-link" data-size="1000x667">
              <img src="/assets/greet/images/phr/21587329_891989314283283_4888037390214767349_o.jpg" alt="">
            </a>
          </div>

          <div class="item-folio__text">
            <h3 class="item-folio__title">
              Смачного пиффка в наших забігайлівках і рок-н-ролу)
            </h3>
          </div><!-- end item-folio -->
        </div>
      </div>

    </div> <!-- end masonry -->
  </div> <!-- end masonry-wrap -->
</section>

<footer class="text-center" style="background: #0f0f0f; padding: 25px 0;">
  <p style="color: white;" >Made for fun but with <i class="fa fa-heart" aria-hidden="true"></i></p>
  <p style="color: white;" >PS. Свій подарунок шукай в джунглях</i></p>
</footer>
<div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">

  <div class="pswp__bg"></div>
  <div class="pswp__scroll-wrap">

    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>

    <div class="pswp__ui pswp__ui--hidden">
      <div class="pswp__top-bar">
        <div class="pswp__counter"></div>
        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
        <button class="pswp__button pswp__button--share" title=
        "Share"></button>
        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
        <button class="pswp__button pswp__button--zoom" title=
        "Zoom in/out"></button>
        <div class="pswp__preloader">
          <div class="pswp__preloader__icn">
            <div class="pswp__preloader__cut">
              <div class="pswp__preloader__donut"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>
      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
      <button class="pswp__button pswp__button--arrow--right" title=
      "Next (arrow right)"></button>
      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>
    </div>

  </div>

</div> <!-- end photoSwipe background -->


<!-- preloader
================================================== -->
<div id="preloader">
  <div id="loader">
  </div>
</div>


<!-- Java Script
================================================== -->
<script src="/assets/greet/js/jquery-3.2.1.min.js"></script>
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
<script src="/assets/greet/js/plugins.js"></script>
<script src="/assets/greet/js/main.js"></script>

</body>

</html>