<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Крч......................................................................................................................все?</title>
    <script type="text/javascript">
      window.App = {
        Settings: {
          root: '/'
        }
      };
    </script>
</head>
<body>
<p>Щастя-здоровля крч...</p>
<p style="color:#fff">
    Якщо ти подумала, що то все, то значить я зря старався і ти ніколи не побачиш ту прикольну фігню, яку я приготував тут...
</p>
<!--<p>
    Тобі треба буде трохи поколупатися в інструментах браузера і найти справжнє привітання, якщо хочеш, звісно... До мене не пиши, цю загадку ти повинна рішити сама. Попроси допомоги в полоскуна чи ще кого, хто трохи шарить в компудахтерах, на крайняк, Скелетон клік, вони люблять загадки по сайтах розбирати). А можливо, сама розберешся, було б круто
</p>-->
</body>
<script src="/assets/libs/jQuery/jquery-3.2.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="/assets/js/common.js"></script>
<script type="text/javascript" src="/assets/js/mystery.js"></script>
<script type="text/javascript">
  App.Page.Mystery();
</script>
</html>