<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="text/css" rel="stylesheet" href="/assets/css/greeting.css"/>
    <title>Терпіння, мій пернатий друже...</title>
    <script type="text/javascript">
      window.App = {
        Settings: {
          root: '/'
        }
      };
    </script>
</head>
<body>
<h3>Лишилось:</h3>
<h1 id="timer"></h1>
</body>
<script src="/assets/libs/jQuery/jquery-3.2.0.min.js"></script>
<script src="/assets/js/common.js"></script>
<script type="text/javascript" src="/assets/js/timer.js"></script>
<script type="text/javascript">
  App.Page.Greeting({
    target: "<?=$target_date->format('Y-m-d H:i:s');?>"
  });
</script>
</html>