<div class="page-header">
	<h1>Учасники групи
		<small>тут можна додати учасника</small>
	</h1>
</div>

<form enctype="multipart/form-data" class="form" method="post">
	<div class="form-group">
		<input class="form-control header-news" name="name" placeholder="Ім'я" type="text" value="">
		<span id="error"></span>
	</div>
	<div class="form-group">
		<input class="form-control header-news" name="position" placeholder="Інструмент" type="text" value="">
	</div>
	<div class="form-group">
		<input class="form-control"  name="pic" placeholder="Пікча" type="file" value="">		
	</div>
	<div class="form-group">
		<select class="form-control" name="isCurrent">
			<option value="1" selected="selected">Грає</option>
			<option value="0">Пішов з групи</option>
		</select>
	</div>
	<div class="form-group">
		<select class="form-control" name="display">
			<option value="1" selected="selected">Показувати</option>
			<option value="0">Приховати</option>
		</select>
	</div>
	<div class="form-group">
		<textarea class="form-control" name="text" id="text"></textarea>		
	</div>
	<div class="form-group">	
		<button type="submit" name="submit" class="btn btn-primary save">
		<i class="fa fa-check"></i>
			Додати учасника
		</button>
		<a href="/admin/about" class="btn btn-default">
			<i class="fa fa-long-arrow-left"></i>
				Назад
		</a>
	</div>
</form>
