<div class="page-header">
	<h1>Учасники групи
		<small>тут можна додавати, редагувати та видаляти учасників</small>
	</h1>	
</div>
<?=(!empty($feedback)) ? $feedback : ''?>
<a href="/admin/about/create/" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Додати учасника</a>
<div class="clearfix"></div>
 <div class="table-container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Ім'я</th>
				<th>Інструмент</th>
				<th>Фото</th>
				<th>Ще грає?</th>
				<th>Показувати</th>
				<th>Дії</th>
			</tr>
		</thead>
		<tbody>
		<?php if (count($people) > 0) :?>
			<?php foreach($people as $person) :?>
			<tr data-id="<?=$person->id ?>">
				<td>
					<?=$person->name?>
				</td>
				<td>
					<?=$person->position ?>
				</td>
				<td class="pic-in-td">
					<?php if (!empty($person->pic)) :?>
						<img src="/upload/images/people/thumbs/<?=$person->pic?>" class="img-responsive" />
					<?php else :?>
						<img src="http://placehold.it/100x70?text=:(" class="img-responsive" />
					<?php endif;?>
				</td>
				<td>
					<?php if ($person->isCurrent) :?>
					Грає
					<?php else :?>
					Пішов з групи
					<?php endif;?>					
				</td>
				<td>
					<?php if ($person->display) :?>
					Показувати
					<?php else :?>
					Приховати
					<?php endif;?>					
				</td>
				<td>
					<div class="btn-group-vertical">
						<a href="/admin/about/update/<?=$person->id ?>" title="Редагувати" class="btn btn-primary">
							<i class="fa fa-edit"></i>
						</a> 
						<a href="#modal" data-toggle='modal' title="Видалити" data-link="/admin/about/delete/<?=$person->id ?>" class="btn btn-danger delete">
							<i class="fa fa-times"></i>
						</a> 
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		<?php else :?>
			<td colspan="6" class="cell-middle">
				<div class="note note-info text-center">
				    <h4>
				        Немає учасників, поки що...
				    </h4>			    
				</div>
			</td>
		<?php endif;?>
		</tbody>		
	</table>
 </div>
<div style="display: none;" class="modal fade" id="modal" role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header borderless">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
				<h4 class="modal-title">Видалити учасника?</h4>
			</div>
			<div class="modal-body">
				<form method="post" class = "delete_form">
					<input type="hidden" name="id" class="id-modal" />
					<button type="submit" name ="submit" class="btn btn-danger">
						Так
					</button>
					<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">
						Ні 
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('.delete').on("click", function () {
	var link = $(this).closest("a.delete");
	var	url = link.data("link");
	var tr = $(this).closest("tr");
	var	id = tr.data("id");
	$('.delete_form').attr("action", url);
	$('.id-modal').attr("value", id);
});
</script>