<div class="page-header">
	<h1>Учасники групи
		<small>ви редагуєте учасника <strong><?=$person->name?></strong></small>
	</h1>
</div>

<form enctype="multipart/form-data" class="form" method="post">
	<div class="form-group">
		<input class="form-control" name="name" placeholder="Ім'я" type="text" value="<?=$person->name?>">
		<span id="error"></span>
	</div>
	<div class="form-group">
		<input class="form-control" name="position" placeholder="Інструмент" type="text" value="<?=$person->position?>">
	</div>
	<?php if (!empty($person->pic)):?>
	<img src="/upload/images/people/thumbs/<?=$person->pic?>" />
	<?php endif;?>
	<div class="form-group">
		<input class="form-control"  name="pic" placeholder="Пікча" type="file">		
	</div>	
	<div class="form-group">
		<select class="form-control" name="isCurrent">
			<option value="1" <?=($person->isCurrent) ? "selected" : null ?>>Грає</option>
			<option value="0" <?=($person->isCurrent) ? null : "selected"?>>Пішов з групи</option>
		</select>
	</div>
	<div class="form-group">
		<select class="form-control" name="display">
			<option value="1" <?=($person->display) ? "selected" : null ?>>Показувати</option>
			<option value="0" <?=($person->display) ? null : "selected"?> >Приховати</option>
		</select>
	</div>
	<div class="form-group">
		<textarea class="form-control" name="text" id="text"><?=$person->text?></textarea>		
	</div>
		
	<button type="submit" name="submit" class="btn btn-primary save">
	<i class="fa fa-check"></i>
		Зберегти
	</button>
	<a href="/admin/about" class="btn btn-default">
		<i class="fa fa-long-arrow-left"></i>
		Назад
	</a>	
</form>