<div class="page-header">
	<h1>Каталог фотографій
		<small>ви редагуєте каталог <strong><?=$photocat->name?></strong></small>
	</h1>
</div>

<form method="post" enctype="multipart/form-data">
	<div class="form-group">
		<label> Назва категорії </label>
		<input class="form-control" required name="name" placeholder="Назва категорії" type="text" value = "<?=$photocat->name?>">
	</div>
    <div class="form-group">
        <input class="form-control" required name="sort_order" placeholder="Порядковий номер" type="text" value = "<?=$photocat->sort_order?>">
    </div>
    <?php if ($photocat->pic != '') :?>
    	<img src="/upload/photos/<?=$photocat->folder?>/thumbs/<?=$photocat->pic?>" />
    <?php endif; ?>
    <div class="form-group">
        <input class="form-control"  name="pic" placeholder="Пікча" type="file">
    </div>	
	<button type="submit" name="submit" class="btn btn-primary save">
	<i class="fa fa-check"></i>
		Зберегти
	</button>
	<a href="/admin/photo" class="btn btn-default">
		<i class="fa fa-long-arrow-left"></i>
		Назад
	</a>	
</form>