<div class="page-header">
	<h1>Відео
		<small>тут можна створити відео</small>
	</h1>
</div>

<form class="form" method="post">
	<div class="form-group">
		<input class="form-control" name="title" placeholder="Заголовок" type="text" value="">
		<span id="error"></span>
	</div>
	<div class="form-group">
		<input class="form-control" name="sort_order" placeholder="Порядковий №" type="text" value="">
	</div>
	<div class="form-group">
		<input class="form-control" name="url" placeholder="Ідентифікатор відео Youtube" type="text" value="">
		<span id="error"></span>
	</div>		
	<button type="submit" name="submit" class="btn btn-primary save">
	<i class="fa fa-check"></i>
		Створити відео
	</button>
	<a href="/admin/video" class="btn btn-default">
		<i class="fa fa-long-arrow-left"></i>
		Назад
	</a>	
</form>