<link href="/assets/css/pages/adminvideo.css" rel="stylesheet" />
<div class="page-header">
	<h1>Відео
		<small>тут можна додавати, редагувати та видаляти відео</small>
	</h1>
</div>
<?=(!empty($feedback)) ? $feedback : ''?>
<a href="/admin/video/create/" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Створити відео</a>
<div class="clearfix"></div>
<div class="row">
	<?php if (count($video) === 0 ) :?>
		<div class="col-md-12 mg-tp-25">
			<div class="note note-info">
				<h4>
					Немає жодного відео
				</h4>
			</div>
		</div>
	<?endif ;?>
	<?php foreach ($video as $vid) :?>	
		<div class="col-md-4 video">
			<h3 class="video-title">
				<?=$vid->title?>
			</h3>
			<div style="position:relative;height:0;padding-bottom:56.25%; margin-bottom: 10px;">
				<iframe src="https://www.youtube.com/embed/<?=$vid->url?>?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe>
			</div>			
			<div class="btn-group">
				<a href="/admin/video/update/<?=$vid->id ?>" title="Редагувати" class="btn btn-primary">
					<i class="fa fa-edit"></i>
					Редагувати
				</a> 
				<a href="#modal" data-toggle='modal' title="Видалити" data-link="/admin/video/delete/<?=$vid->id ?>" class="btn btn-danger delete">
					<i class="fa fa-times"></i>
					Видалити
				</a>
			</div>
		</div>	
	<?php endforeach;?>
</div>


 <!--<div class="table-container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Заголовок</th>
				<th>Місце</th>
				<th>Афіша</th>
				<th>Дата та час</th>
				<th>Дії</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($news as $new) :?>
			<tr data-id="<?=$new->id ?>">
				<td>
					<?=$new->title?>
				</td>
				<td>
					<?=$new->place ?>
				</td>
				<td class="pic-in-td">
					<?php if (!empty($new->pic)) :?>
						<img src="/upload/images/posts/thumbs/<?=$new->pic?>" class="img-responsive" />
					<?php else :?>
						<img src="http://placehold.it/100x70?text=:(" class="img-responsive" />
					<?php endif;?>
				</td>
				<td>
					<?=date_format(date_create($new->date), 'd-m-Y');?>
					<br>
					<?=date_format(date_create($new->time), 'H:i');?>
				</td>
				<td>
					<div class="btn-group-vertical">
						<a href="/admin/news/update/<?=$new->id ?>" title="Редагувати" class="btn btn-primary">
							<i class="fa fa-edit"></i>
						</a> 
						<a href="#modal" data-toggle='modal' title="Видалити" data-link="/admin/news/delete/<?=$new->id ?>" class="btn btn-danger delete">
							<i class="fa fa-times"></i>
						</a> 
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>		
	</table>
 </div>-->
<div style="display: none;" class="modal fade" id="modal" role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header borderless">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
				<h4 class="modal-title">Видалити відео?</h4>
			</div>
			<div class="modal-body">
				<form method="post" class = "delete_form">
					<input type="hidden" name="id" class="id-modal" />
					<button type="submit" name ="submit" class="btn btn-danger">
						Так
					</button>
					<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">
						Ні 
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('.delete').on("click", function () {
	var link = $(this).closest("a.delete");
	var	url = link.data("link");
	var tr = $(this).closest("tr");
	var	id = tr.data("id");
	$('.delete_form').attr("action", url);
	$('.id-modal').attr("value", id);
});
</script>