<div class="page-header">
	<h1>Музика
		<small>тут можна додавати, редагувати та видаляти музику</small>
	</h1>
</div>
<?=(!empty($feedback)) ? $feedback : ''?>
<a href="/admin/music/add" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Додати пісню</a>
<div class="clearfix"></div>
 <div class="table-container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Порядок</th>
				<th>Назва</th>				
				<th>Автор</th>
				<th>Аудіо</th>
				<th>Обкладинка</th>
				<th>Дії</th>
			</tr>
		</thead>
		<tbody>
		<?php if (count($music) > 0) :?>
			<?php foreach($music as $song) :?>
			<tr data-id="<?=$song->id ?>">
				<td>
					<?=$song->sort_order ?>
				</td>
				<td>
					<?=$song->title?>
				</td>
				<td>
					<?=$song->author?>
				</td>				
				<td>
					<?php if (!empty($song->songFileName)) :?>
						<audio src="<?=$song->songUrl?>" controls="controls" /></audio>
					<?php else :?>
						<img src="http://placehold.it/100x30?text=немає+файлу" class="img-responsive" />
					<?php endif;?>
				</td>
				<td class="pic-in-td">
					<?php if (!empty($song->picFileName)) :?>
						<img src="<?=$song->picUrl?>" class="img-responsive" />
					<?php else :?>
						<img src="http://placehold.it/100x70?text=:(" class="img-responsive" />
					<?php endif;?>
				</td>
				<td>
					<div class="btn-group-vertical">
						<a href="/admin/music/update/<?=$song->id ?>" title="Редагувати" class="btn btn-primary">
							<i class="fa fa-edit"></i>
						</a> 
						<a href="#modal" data-toggle='modal' title="Видалити" data-link="/admin/music/remove/<?=$song->id ?>" class="btn btn-danger delete">
							<i class="fa fa-times"></i>
						</a> 
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		<?php else :?>
			<td colspan="6" class="cell-middle">
				<div class="note note-info text-center">
				    <h4>
				        Немає музики, поки що...
				    </h4>			    
				</div>
			</td>
		<?php endif;?>
		</tbody>		
	</table>
 </div>
<div style="display: none;" class="modal fade" id="modal" role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header borderless">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
				<h4 class="modal-title">Видалити пісню?</h4>
			</div>
			<div class="modal-body">
				<form method="post" class = "delete_form">
					<input type="hidden" name="id" class="id-modal" />
					<button type="submit" name ="submit" class="btn btn-danger">
						Так
					</button>
					<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">
						Ні 
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('.delete').on("click", function () {
	var link = $(this).closest("a.delete");
	var	url = link.data("link");
	var tr = $(this).closest("tr");
	var	id = tr.data("id");
	$('.delete_form').attr("action", url);
	$('.id-modal').attr("value", id);
});
</script>