<div class="page-header">
	<h1>Новинами
		<small>ви редагуєте новину <strong><?=$new->title?></strong></small>
	</h1>
</div>

<form enctype="multipart/form-data" class="form" method="post">
	<div class="form-group">
		<input class="form-control header-news" name="title" placeholder="Заголовок" type="text" value="<?=$new->title?>">
		<span id="error"></span>
	</div>
	<div class="form-group">
		<input class="form-control header-news" name="place" placeholder="Місце" type="text" value="<?=$new->place?>">
	</div>
	<?php if (!empty($new->pic)):?>
	<img src="/upload/images/posts/thumbs/<?=$new->pic?>" />
	<?php endif;?>
	<div class="form-group">
		<input class="form-control"  name="pic" placeholder="Пікча" type="file">		
	</div>	
	<div class="form-group">
		<input class="form-control"  name="date" placeholder="Дата" type="date" value="<?=$new->date?>">
	</div>
	<?php
	$hours = substr($new->time, 0, 2);
	$mins = substr($new->time, 3, 2);
	?>
	<div class="form-group">
		<input class="form-inline" name="hours" placeholder="Години" type="number" min="00" max="23" style="color: #000;" value="<?=$hours?>">
		<input class="form-inline" name="mins" placeholder="Хвилини" type="number" min="00" max="59" style="color: #000;" value="<?=$mins?>">
	</div>
	<div class="form-group">
		<textarea class="form-control" name="newtext" id="textnews" type="text"><?=$new->newtext?></textarea>		
	</div>
		
		<button type="submit" name="submit" class="btn btn-primary save">
		<i class="fa fa-check"></i>
			Запілить новину
		</button>
		<a href="/admin/news" class="btn btn-default">
			<i class="fa fa-long-arrow-left"></i>
				Назад
		</a>
	</div>
</form>
<script>
	CKEDITOR.replace('textnews');
</script>